/**
 * FlightBookingAPI
 * API aplikacije za kupovinu avionskih karata
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Podaci o dolasku leta.
 */
export interface Arrival { 
    /**
     * Vreme i datum dolaska.
     */
    time: string;
    /**
     * Mesto dolaska.
     */
    city: string;
}

