/**
 * FlightBookingAPI
 * API aplikacije za kupovinu avionskih karata
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserFlightTicket } from './userFlightTicket';


/**
 * Rezultat kupovine karata odabranog korisnika.
 */
export interface FlightBuyTicketsResponse { 
    /**
     * Podaci o kupljenim kartama.
     */
    flightTickets: Array<UserFlightTicket>;
}

