/**
 * FlightBookingAPI
 * API aplikacije za kupovinu avionskih karata
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserFlightTicket } from './userFlightTicket';


/**
 * Podaci o svim kupljenim kartama za let odabranog korisnika.
 */
export interface UserFlightTicketGetAllResponse { 
    /**
     * Podaci o kupljenim kartama za let.
     */
    flightTickets: Set<UserFlightTicket>;
}

