services:
  lodge-spot-mq:
    image: rabbitmq:3.11.7-management
    container_name: lodge-spot-mq
    hostname: lodge-spot-mq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: user
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - mq-lodge-data:/var/lib/rabbitmq
      - mq-lodge-log:/var/log/rabbitmq
volumes:
  mq-lodge-data:
  mq-lodge-log: