:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore src\FlightsBookingAPI
dotnet build src\FlightsBookingAPI
echo Now, run the following to start the project: dotnet run -p src\FlightsBookingAPI\FlightsBookingAPI.csproj --launch-profile web.
echo.
