/**
 * FlightBookingAPI
 * API aplikacije za kupovinu avionskih karata
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Departure } from './departure';
import { Arrival } from './arrival';


/**
 * Model za kreiranje novog leta.
 */
export interface FlightCreateRequest { 
    departure: Departure;
    arrival: Arrival;
    /**
     * Ukupan broj karata za let.
     */
    totalTickets: number;
    /**
     * Cena karte leta.
     */
    ticketPrice: number;
}

