/**
 * FlightBookingAPI
 * API aplikacije za kupovinu avionskih karata
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Departure } from './departure';
import { Arrival } from './arrival';


/**
 * Model koji predstavlja podatke o letu.
 */
export interface UserFlight { 
    /**
     * Jedinstveni identifikator leta.
     */
    flightId: string;
    departure: Departure;
    arrival: Arrival;
    /**
     * Podatak o tome da li je proslo vreme polaska.
     */
    passed: boolean;
    /**
     * Podatak o tome da li je let otkazan.
     */
    canceled: boolean;
}

