/**
 * FlightBookingAPI
 * API aplikacije za kupovinu avionskih karata
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserFlight } from './userFlight';


/**
 * Podaci o kupljenoj karti za let.
 */
export interface UserFlightTicket { 
    /**
     * Identifikator karte leta.
     */
    flightTicketId: string;
    /**
     * Trenutak kada je karta kupljena.
     */
    purchased: string;
    /**
     * Cena karte u trenutku kupovine.
     */
    price: number;
    flight: UserFlight;
}

