version: "3.8"
services:
  accommodation-suggestion-service:
    image: bookingappcontainers.azurecr.io/accommodation-suggestion-service:1.0.0
    container_name: accommodation-suggestion-service
    environment:
      ASPNETCORE_ENVIRONMENT : Cloud
      MongoDatabaseSettings:ConnectionString: mongodb+srv://svenadev:0mSCxqslvdQV46wi@booking-app.udfgsob.mongodb.net/?retryWrites=true&w=majority
      Jwt:Authority: https://login-keycloak.azurewebsites.net/auth/realms/booking-app
      Jwt:AuthorizationUrl: https://login-keycloak.azurewebsites.net/auth/realms/booking-app/protocol/openid-connect/auth
      Jwt:TokenUrl: https://login-keycloak.azurewebsites.net/auth/realms/booking-app/protocol/openid-connect/token