version: "3.8"
services:
  ocelot-apigateway:
    image: bookingappcontainers.azurecr.io/ocelot-apigateway:1.0.0
    container_name: ocelot-apigateway
    ports:
      - "80:80"
      - "443:443"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Cloud