version: "3.8"
services:
  accommodation-grading-service:
    image: bookingappcontainers.azurecr.io/accommodation-grading-service:1.0.0
    container_name: accommodation-grading-service
    build:
      context: ../../backend/Accomodation
      dockerfile: ./AccomodationGrading/Dockerfile 
    environment:
      ASPNETCORE_ENVIRONMENT : Cloud
      MongoDatabaseSettings:ConnectionString: mongodb+srv://svenadev:0mSCxqslvdQV46wi@booking-app.udfgsob.mongodb.net/?retryWrites=true&w=majority
      Jwt:Authority: https://login-keycloak.azurewebsites.net/auth/realms/booking-app
      Jwt:AuthorizationUrl: https://login-keycloak.azurewebsites.net/auth/realms/booking-app/protocol/openid-connect/auth
      Jwt:TokenUrl: https://login-keycloak.azurewebsites.net/auth/realms/booking-app/protocol/openid-connect/token
  accommodation-suggestion-service:
    image: bookingappcontainers.azurecr.io/accommodation-suggestion-service:1.0.0
    container_name: accommodation-suggestion-service
    build:
      context: ../../backend/Accomodation
      dockerfile: ./AccomodationSuggestion/Dockerfile 
    environment:
      ASPNETCORE_ENVIRONMENT : Cloud
      MongoDatabaseSettings:ConnectionString: mongodb+srv://svenadev:0mSCxqslvdQV46wi@booking-app.udfgsob.mongodb.net/?retryWrites=true&w=majority
      Jwt:Authority: https://login-keycloak.azurewebsites.net/auth/realms/booking-app
      Jwt:AuthorizationUrl: https://login-keycloak.azurewebsites.net/auth/realms/booking-app/protocol/openid-connect/auth
      Jwt:TokenUrl: https://login-keycloak.azurewebsites.net/auth/realms/booking-app/protocol/openid-connect/token
  accommodation-service:
    image: bookingappcontainers.azurecr.io/accommodation-service:1.0.0
    container_name: accommodation-service
    build:
      context: ../../backend/Accomodation
      dockerfile: ./Accomodation/Dockerfile 
    environment:
      ASPNETCORE_ENVIRONMENT : Development
      MongoDatabaseSettings:ConnectionString: mongodb+srv://svenadev:0mSCxqslvdQV46wi@booking-app.udfgsob.mongodb.net/?retryWrites=true&w=majority
      Jwt:Authority: https://login-keycloak.azurewebsites.net/auth/realms/booking-app
      Jwt:AuthorizationUrl: https://login-keycloak.azurewebsites.net/auth/realms/booking-app/protocol/openid-connect/auth
      Jwt:TokenUrl: https://login-keycloak.azurewebsites.net/auth/realms/booking-app/protocol/openid-connect/token
  ocelot-apigateway:
    image: bookingappcontainers.azurecr.io/ocelot-apigateway:1.0.0
    container_name: ocelot-apigateway
    build:
      context: ../../backend/Accomodation
      dockerfile: ./Accomodation.ApiGateway/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Cloud
  booking-webapp:
    image: bookingappcontainers.azurecr.io/booking-webapp:1.0.0
    container_name: booking-webapp
    build:
      context: ../../accommodation-frontend
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
  flights-booking-service:
    image: bookingappcontainers.azurecr.io/flights-booking-service:1.0.0
    container_name: flights-booking-service
    build:
      context: ../../backend/flights-booking-api
      dockerfile: ./src/FlightsBookingApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT : Development
      ENABLE_CORS: true
      MongoDatabaseSettings:ConnectionString: mongodb+srv://svenadev:0mSCxqslvdQV46wi@booking-app.udfgsob.mongodb.net/?retryWrites=true&w=majority
      Jwt:Authority: https://login-keycloak.azurewebsites.net/auth/realms/booking-app
      Jwt:AuthorizationUrl: https://login-keycloak.azurewebsites.net/auth/realms/booking-app/protocol/openid-connect/auth
      Jwt:TokenUrl: https://login-keycloak.azurewebsites.net/auth/realms/booking-app/protocol/openid-connect/token
  flights-webapp:
    image: bookingappcontainers.azurecr.io/flights-webapp:1.0.0
    container_name: flights-webapp
    build:
      context: ../../frontend
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
  notification-service:
    image: bookingappcontainers.azurecr.io/notification-service:1.0.0
    container_name: notification-service
    build:
      context: ../../backend/Accomodation
      dockerfile: ./Notification/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT : Cloud
      MongoDatabaseSettings:ConnectionString: mongodb+srv://svenadev:0mSCxqslvdQV46wi@booking-app.udfgsob.mongodb.net/?retryWrites=true&w=majority
      Jwt:Authority: https://login-keycloak.azurewebsites.net/auth/realms/booking-app
      Jwt:AuthorizationUrl: https://login-keycloak.azurewebsites.net/auth/realms/booking-app/protocol/openid-connect/auth
      Jwt:TokenUrl: https://login-keycloak.azurewebsites.net/auth/realms/booking-app/protocol/openid-connect/token
  user-management-service:
    image: bookingappcontainers.azurecr.io/user-management-service:1.0.0
    container_name: user-management-service
    build:
      context: ../../backend/Accomodation
      dockerfile: ./UserManagement/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT : Cloud
      MongoDatabaseSettings:ConnectionString: mongodb+srv://svenadev:0mSCxqslvdQV46wi@booking-app.udfgsob.mongodb.net/?retryWrites=true&w=majority
      Jwt:Authority: https://login-keycloak.azurewebsites.net/auth/realms/booking-app
      Jwt:AuthorizationUrl: https://login-keycloak.azurewebsites.net/auth/realms/booking-app/protocol/openid-connect/auth
      Jwt:TokenUrl: https://login-keycloak.azurewebsites.net/auth/realms/booking-app/protocol/openid-connect/token