version: "3.8"
services:
  flights-booking-service:
    image: bookingappcontainers.azurecr.io/flights-booking-service:1.0.0
    container_name: flights-booking-service
    environment:
      ASPNETCORE_ENVIRONMENT : Development
      ENABLE_CORS: true
      MongoDatabaseSettings:ConnectionString: mongodb+srv://svenadev:0mSCxqslvdQV46wi@booking-app.udfgsob.mongodb.net/?retryWrites=true&w=majority
      Jwt:Authority: https://login-keycloak.azurewebsites.net/auth/realms/booking-app
      Jwt:AuthorizationUrl: https://login-keycloak.azurewebsites.net/auth/realms/booking-app/protocol/openid-connect/auth
      Jwt:TokenUrl: https://login-keycloak.azurewebsites.net/auth/realms/booking-app/protocol/openid-connect/token