version: "3.8"
services:
  user-management-service:
    image: bookingappcontainers.azurecr.io/user-management-service:1.0.0
    container_name: user-management-service
    environment:
      ASPNETCORE_ENVIRONMENT : Development
      MongoDatabaseSettings:ConnectionString: mongodb+srv://svenadev:0mSCxqslvdQV46wi@booking-app.udfgsob.mongodb.net/?retryWrites=true&w=majority
      Jwt:Authority: https://login-keycloak.azurewebsites.net/auth/realms/booking-app
      Jwt:AuthorizationUrl: https://login-keycloak.azurewebsites.net/auth/realms/booking-app/protocol/openid-connect/auth
      Jwt:TokenUrl: https://login-keycloak.azurewebsites.net/auth/realms/booking-app/protocol/openid-connect/token